### ISSUE TITLE
Unable to run Demo Test

### ISSUE THREAD

**Issue by simbro** [mucsi96/nightwatch-cucumber#205]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**

Set up and run small example based on a code from "simple example" in repo.

This the result of running the test:

```
Feature: Google Search

  Scenario: Searching Google
  × Given I open Google's search page
  - Then the title is "Google"
  - And the Google search form exists

Failures:

1) Scenario: Searching Google - features\google.feature:5
   Step: Given I open Google's search page - features\google.feature:7
   Step Definition: features\step_definitions\google.js:7
   Message:
     TypeError: client.url is not a function
         at World.Given (C:\Users\admin\Desktop\test_test\features\step_definitions\google.js:9:8)
```

**Expected/desired behavior**

Expected tests to pass.

**Reproduction of the problem**

_npm init_
_npm i -D nightwatch@0.9.9_
_npm i -D cucumber@2.0.0-rc.9_
_npm i -D nightwatch-cucumber@7.1.0_
_npm i -D phantomjs-prebuilt@2.1.14_
_npm i -D selenium-server-standalone-jar@3.3.1_

_mkdir features_
_mkdir features/step_definitions_

_vim features/google.feature_

```
# features/google.feature

Feature: Google Search

Scenario: Searching Google

  Given I open Google's search page
  Then the title is "Google"
  And the Google search form exists
```

_vim features/step_definitions/google.js_

```
// features/step_definitions/google.js

const {client} = require('nightwatch-cucumber');
const {defineSupportCode} = require('cucumber');

defineSupportCode(({Given, Then, When}) => {
  Given(/^I open Google's search page$/, (client) => {
    return client
      .url('http://google.com')
      .waitForElementVisible('body', 1000);
  });

  Then(/^the title is "([^"]*)"$/, (client, title) => {
    return client.assert.title(title);
  });

  Then(/^the Google search form exists$/, (client) => {
    return client.assert.visible('input[name="q"]');
  });

});
```

_vim nightwatch.conf.js_

```
require('nightwatch-cucumber')({
  cucumberArgs: ['--require', 'timeout.js', '--require', 'features/step_definitions', '--format', 'pretty', '--format', 

'json:reports/cucumber.json', 'features']
})

module.exports = {
  output_folder: 'reports',
  custom_assertions_path: '',
  live_output: false,
  disable_colors: false,
  selenium: {
    start_process: true,
    server_path: './node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone-3.3.1.jar',
    log_path: '',
    host: '127.0.0.1',
    port: 4444
  },
  test_settings: {
    default: {
      launch_url: 'http://localhost:8087',
      selenium_port: 4444,
      selenium_host: '127.0.0.1',
      desiredCapabilities: {
        browserName: 'phantomjs',
        javascriptEnabled: true,
        acceptSslCerts: true,
        'phantomjs.binary.path': './node_modules/phantomjs-prebuilt/bin/phantomjs'
      }
    }
  }
}
```

_vim timeout.js_

```
const {defineSupportCode} = require('cucumber')

defineSupportCode(({setDefaultTimeout}) => {
  setDefaultTimeout(30 * 1000)
})
```

_node ./node_modules/nightwatch/bin/runner.js_

**What is the expected behavior?**

Expected all tests to pass, but getting error mesage described above, TypeError: client.url is not a function at World.Given

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **nightwatch-cucumber version:** 7.1.0

* **nightwatch version:** 0.9.9

* **cucumber version:** 2.0.0-rc.9

* **Node.js version:** 6.9.1
