### ISSUE TITLE
Error: No source folder defined

### ISSUE THREAD

**Issue by subhojit777** [mucsi96/nightwatch-cucumber#224]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
With the new 7.1.5 release when I run the test I am getting
```
Error: No source folder defined. Check configuration
```

While this was not happening in 7.1.2 release.

**Expected/desired behavior**
Should run the tests.

**Please tell us about your environment:**

* **nightwatch-cucumber version:**
`nightwatch-cucumber@7.1.5`

* **nightwatch version:**
`nightwatch@0.9.15`

* **cucumber version:**
`cucumber@2.1.0`

* **Node.js version:**
`v6.10.2`

* **npm version:**
`3.10.10`

**Comment by mucsi96** [comment]
Hi Paul! Thanks for feedback! Is nightwatch and cucumber installed locally? What is your npm version? Also please provide the full console output.

**Comment by subhojit777** [comment]
Actually everything is running inside a Docker container.

Here is the console output:

```
Waiting for chromedriver:4444 to become available ... done
Waiting for chromedriver:6060 to become available ... done
There was an error while starting the test runner:

Error: No source folder defined. Check configuration.
    at Function.Runner.readPaths (/usr/lib/node_modules/nightwatch/lib/runner/run.js:189:11)
    at Runner.runner [as run] (/usr/lib/node_modules/nightwatch/lib/runner/run.js:232:10)
    at Object.runner (/usr/lib/node_modules/nightwatch/lib/runner/cli/clirunner.js:443:23)
    at /usr/lib/node_modules/nightwatch/lib/runner/cli/clirunner.js:395:12
    at /usr/lib/node_modules/nightwatch/lib/runner/cli/clirunner.js:337:9
    at Object.beforeGlobal (/usr/lib/node_modules/nightwatch/lib/runner/cli/clirunner.js:333:89)
    at Object.startSelenium (/usr/lib/node_modules/nightwatch/lib/runner/cli/clirunner.js:336:20)
    at Object.runTests (/usr/lib/node_modules/nightwatch/lib/runner/cli/clirunner.js:393:10)
    at Object.exports.runner (/usr/lib/node_modules/nightwatch/lib/index.js:551:39)
    at /usr/lib/node_modules/nightwatch/bin/runner.js:10:16
    at Object.exports.cli (/usr/lib/node_modules/nightwatch/lib/index.js:545:5)
    at Object.<anonymous> (/usr/lib/node_modules/nightwatch/bin/runner.js:8:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

I have added the npm version in the issue description.

**Comment by mucsi96** [comment]
Thanks I will check today or tomorrow

**Comment by mucsi96** [comment]
Hi Paul! Can you send me a complete runnable example in ZIP(without including node_modules)? Also a dockerfile would be helpful. If you don't what to share you project source please create a dummy example where the issue is reproducible.

**Comment by subhojit777** [comment]
`package.json`
----------------

```json
{
  "name": "blueimp-nightwatch-example",
  "private": true,
  "devDependencies": {
    "cucumber": "^2.0.0-rc.9",
    "nightwatch": "^0.9.15",
    "nightwatch-cucumber": "^7.1.1"
  }
}
```

`docket-compose.yml`
------------------------

```yml
version: '2'
services:
  chromedriver:
    image: blueimp/chromedriver
    environment:
      - VNC_ENABLED=true
      - EXPOSE_X11=true
    ports:
      - 5900:5900
  nightwatch:
    image: subhojit777/nightwatch:latest
    environment:
      - WAIT_FOR_HOSTS=chromedriver:4444 chromedriver:6060
    depends_on:
      - chromedriver
    volumes:
      - .:/home/node
```

The feature files are normal.
